-- MySQL Script generated by MySQL Workbench
-- Ter 20 Jun 2017 18:07:58 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydontpad
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydontpad
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydontpad` DEFAULT CHARACTER SET utf8 ;
USE `mydontpad` ;

-- -----------------------------------------------------
-- Table `mydontpad`.`caderno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydontpad`.`caderno` (
  `id_caderno` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `conteudo` VARCHAR(255) NULL,
  `publico` TINYINT(1) NULL,
  `criacao` VARCHAR(255) NULL,
  `atualizacao` VARCHAR(255) NULL,
  `id_dono` INT NULL,
  PRIMARY KEY (`id_caderno`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC)) AUTO_INCREMENT=1;


-- -----------------------------------------------------
-- Table `mydontpad`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydontpad`.`usuario` (
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `nome` VARCHAR(255) NULL ,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC)) AUTO_INCREMENT=1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
